# Generated by Django 6.0 on 2026-03-05 01:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Producto',
            new_name='ListaProducto',
        ),
    ]
